### ISSUE TITLE
Quiz app can't run properly?

### ISSUE THREAD

**Issue by yogesh-sonar** [Stefan-Pamparau/Online-quiz-ui#1]
This app cant run successfully. please guide me.

**Comment by Stefan-Pamparau** [comment]
Hello,

This Quiz App was developed as a semester project. Last time I checked it ran just fine.

However, this repo is just the UI. For the entire application you will also need the backend services: https://github.com/Stefan-Pamparau/Online-quiz . Please use the develop branch for the backend services.

Thanks,
Stefan
